### ISSUE TITLE
image not found

### ISSUE THREAD

**Issue by ianmonat** [mikeckennedy/mongodb-quickstart-course#3] opened 2018-01-24 07:17 UTC
![image](https://user-images.githubusercontent.com/20530405/35319038-efa2ed76-0092-11e8-8b30-48c5f85cd2aa.png)

Hi, I seem to be missing an image, which is preventing the Snake BnB app from running in PyCharm. 

This is in the 'Demo:Getting started with the application / demo code' lesson in the Modeling data in document databases module. 

Not sure what image I need or where to retrieve it, thanks. Thanks -Ian

**Comment by mikeckennedy** [comment] 2018-01-24 16:48
Hi @ianmonat, this looks like a python level install error. Basically it seems to have trouble installing dylib?

Is this you running the exact code from this repo or your written version following along? I'll try to reproduce it but maybe also try recreating the venv and try again?

**Comment by ianmonat** [comment] 2018-01-25 06:06
I try to replicate your code exactly except when errors pop up and I need to work around

**Comment by gtmaskall** [comment] 2018-01-31 10:55
I see this error has cropped up before. A couple of useful links for you might be
https://github.com/pre-commit/pre-commit/issues/618
and
https://github.com/ContinuumIO/anaconda-issues/issues/305#issuecomment-285094497

I think your issue may be resolved by getting your anaconda python up to verson 3.6.4 (or at least 3.6.3). Your dylib error may just be a different manifestation of the lack of ensurepip. One comment in the above links suggests updating your python should fix it.

Regards,
Guy

**Closed as completed** 2018-03-07 19:04 UTC
